### ISSUE TITLE
营销号生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#1]
source: https://kaseidis.gitee.io/interesting_gadgets/marketing_generator/index.htm

```toml
[[variables]]
id = "subject"
description = "主题"
default = "桃核"

[[variables]]
id = "event"
description = "描述"
default = "不能整个吞下去"

[[variables]]
id = "reason"
description = "另一种相似的表述"
default = "桃核太大了，吞下去容易噎着"

[templates]
main = [
"""
{subject}{event}是怎么回事呢？{subject}相信大家都很熟悉，但是{event}是怎么回事呢？下面就让小编带大家一起了解吧。

{subject}{event}，其实就是{reason}。那么{subject}为什么会{event}，相信大家都很好奇是怎么回事。大家可能会感到很惊讶，{subject}怎么会{event}呢？但事实就是这样，小编也感到非常惊讶。那么这就是关于{subject}{event}的事情了，大家有没有觉得很神奇呢？

看了今天的内容，大家有什么想法呢？欢迎在评论区告诉小编一起讨论哦。
"""
]
```
