### ISSUE TITLE
防沉迷公告生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#17]
模板来源于网络。

```toml
# variables 是需要用户填入的文本变量，可以有多个，每个对应生成器的一个输入框。

[[variables]]
id = "company"
description = "公司或组织名"
default = "苹果公司"

[[variables]]
id = "software"
description = "软件名"
default = "XCode软件"

[[variables]]
id = "person"
description = "人群"
default = "成年人"

[[variables]]
id = "object"
description = "沉迷的事项"
default = "加班工作"

[[variables]]
id = "time"
description = "开放时间"
default = "周一至周五，其他法定工作日的08时至18时"

[[variables]]
id = "duration"
description = "服务时长"
default = "不超过8小时"

[[variables]]
id = "service"
description = "服务类型"
default = "代码创作"

[[variables]]
id = "id"
description = "绑定证件类型"
default = "社保"

[templates]

# 'main' 模板展开后是最终的输出
main = [
"""
针对{software}防沉迷调整的说明

2021年08月31日

为了积极响应国家出版署下发的《关于进一步严格管理切实防止{person}沉迷{object}的通知》，坚决防止{person}沉迷{object}，切实保护{person}身心健康，{software}将于2021年9月1日完成对{person}防沉迷系统的调整。

根据相关通知的要求：调整后，{software}仅在{time}，向已绑定{id}号码的{person}提供{duration}{service}服务。（不可累计）

同时，{company}将严格落实{person}用户账号实名注册和{id}号码的绑定要求，不以任何形式向未实名注册和绑定{id}号码的{person}提供{service}服务。

由此可能会带来的创作体验的变化，我们将尽快在后期提供处理说明，请关注官方公告。
"""
]
```
