### ISSUE TITLE
沉迷游戏新闻生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#18]
模板素材来源网络。

```toml
[[variables]]
id = "community"
description = "圈子名"
default = "CG"

[[variables]]
id = "software1"
description = "软件名"
default = "3D MAX"

[[variables]]
id = "price1"
description = "价格"
default = "每年8555人民币"

[[variables]]
id = "software2"
description = "软件名"
default = "MAYA"

[[variables]]
id = "price2"
description = "价格"
default = "每年8555人民币"

[[variables]]
id = "software3"
description = "软件名"
default = "Z Brush"

[[variables]]
id = "price3"
description = "价格"
default = "每年5998人民币"

[templates]
main = [
"""
孩子沉迷电脑，真相竟然是……

2021年9月1日，王女士向我社反应，自己家的孩子小王一到周末就玩电脑，每天都盯着一个黑色的界面看一下午。我社记者随即安排进行调查。

据了解小王受网络“{community}”圈子里的网友教唆，正在玩一款叫做“{software1}”的游戏，有时候也会玩“{software2}”和“{software3}”。

但接下来的调查中，触目惊心的真相出现了。记者在网络调查，发现“{software1}”竟然是付费软件，且费用高达令人瞠目结舌的{price1}，“{software2}”的费用也达到了{price2}，“{software3}”也有{price3}的费用。看到这里王女士都要晕过去了。

小王表示，他的同学每个人都有两三款这样的软件，为了达到更高等级，还要购买很多其他的软件，因为家里条件不是太好目前他都没有购买。这类软件，没有未成年识别，没有防沉迷机制，没有消费限制，很多用户会把一整天的时间投入其中，对青少年的影响不可估量。

目前，我社正准备与王女士一同将此事件的情况举报，以响应国家的防沉迷号召。
"""
]
```
