### ISSUE TITLE
恋爱场景生成器

### ISSUE THREAD

**Issue by Lixinran1826** [disksing/sao-gen-gen#21]
```toml
# variables 是需要用户填入的文本变量，可以有多个，每个对应生成器的一个输入框。

[[variables]]
# 每个变量的唯一 id，在模板中通过{id}的形式引用
id = "女朋友对你的昵称"

# 输入框左边的提示信息
description = "请输入主人公的名字"

# 页面初始化时的默认值，建议写一个例子便于用户理解
default = "李自安"

# 第二个变量

[[variables]]
id = "女朋友名字"
description = "请输入女朋友的名字"
default = "星之卡比"

# 模板可以有很多个，每个模板有唯一 id 和文本列表
# 模板可以通过{id}的形式引用变量或其他模板（允许递归调用）
# 当模板展开时，会从列表中随机选一个
# 通过组合模板，可以搞出比较复杂的结构，参考下“胡编生成器”

[templates]

# 2选1
p1 = ["我的{女朋友名字}缓缓地撑起纯白的雨伞朝我走来，夜幕比黄昏稍早一步降临在晚上六点过后的校园。她脚下的高筒靴肆意践踏柏油路上闪烁的水洼，不顾自己被溅湿，毫不犹豫地走上前，将小小的白伞撑向躲在图书馆门前躲雨的我。明明是这么娇小可爱的女孩子，流畅的动作却宛如没落贵族般优雅，我不禁觉得那道身影美丽至极。“久等啦，{女朋友对你的昵称}！“ {女朋友名字}踮起脚尖将我纳入伞下，紧紧贴着我的肩膀。我们依偎着走入霏霏的雨幕。 “谢谢宝贝，你特意从宿舍赶过来吗？” 我从她的手中接过伞。每次看向她可爱的小脸，内心都会像梅雨天突然见到阳光一样变得明朗；只要她小巧的肩头与我的手臂稍稍触碰，我的身体便会径自感到喜悦。 "]

# toml 支持多行文本
p2 = ["""下午两点的阳光轻轻跳跃在{女朋友名字}的睫毛上，她的目光越过二人的电脑屏幕——壁纸都是我们的合照——盈盈地看向我。大三的我们决定一起报名与本校不同的一所高校，在互相勉励的学习之中，我们两个人相处的时间变得越来越多。也许我和{女朋友名字}都是心理比较早熟的孩子，一边营造着只属于我们两个人的内心世界，一边也为即将到来的推免做着准备。成为研究生之后，{女朋友名字}和我共同的未来的轮廓一定也会变得更加清晰一些吧，我不由得期待起来。停滞在鼠标上的指尖忽然被温热柔软的东西包裹，原来是{女朋友名字}的手指，在我看她出神的时候悄悄从对面伸了过来。“{女朋友对你的昵称}，不要总盯着我看啦！”她皱起好看的眉毛娇嗔道，这让我回想起对{女朋友名字}心动的第一天。那时我们与朋友一起去音乐节，在汹涌的人潮中{女朋友名字}努力贴近我，在我的耳边说“我们到前面去看吧！” 于是那一晚，无论听到的是怎样的歌声，我的脑海中总浮现出{女朋友名字}那听起来让人感觉到很舒服的声音。是的，虽然那个时候我还没有清楚地意识到这一点，但是现在想来，我其实是非常喜欢{女朋友名字}的声音的。"""]

# 'main' 模板展开后是最终的输出
main = ["{p1}"
 ,
 "{p2}"]
```
