### ISSUE TITLE
快过年了

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#23]
来源：网络

```toml
# variables 是需要用户填入的文本变量，可以有多个，每个对应生成器的一个输入框。

[[variables]]
id = "subject"
description = "主题"
default = "NAS、HTPC、OpenWrt"

[[variables]]
id = "object"
description = "物品"
default = "大机箱"

[[variables]]
id = "object2"
description = "物品2"
default = "破群晖"

[[variables]]
id = "work"
description = "工作成果"
default = "组了一个RAID 0的ALL IN ONE"

[[variables]]
id = "knowledge"
description = "知识"
default = "刮削器，不懂你的Auto Backup"

[[variables]]
id = "laugh"
description = "笑点"
default = "看爱奇艺还要忍受会员专属广告"

[[variables]]
id = "work2"
description = "工作成果2"
default = "我的儿子装了个黑盒子，开起来嗡嗡响、家里电表走得越来越快了"

[templates]
main = ["快过年了，不要再讨论什么{subject}之类的了。你带你的{object}回到家并不能给你带来任何实质性作用，朋友们兜里掏出一大把钱吃喝玩乐，你默默的在家里摆弄你的{object2}。亲戚朋友吃饭问你收获了什么，你说我{work}，亲戚们懵逼了，你还在心里默默嘲笑他们，笑他们不懂你的{knowledge}，也笑他们{laugh}。你父母的同事都在说自己的子女一年的收获，儿子买了个房，女儿买了个车，姑娘升职加薪了，你的父母默默无言，说{work2}。"]
```
