### ISSUE TITLE
有一点失望

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#24]
来源：网络

```toml
[[variables]]
id = "org"
description = "组织名"
default = "工信部"

[[variables]]
id = "person"
description = "人物"
default = "阿里云"

[[variables]]
id = "time"
description = "当初"
default = "阿里云中标工信部合作单位"

[[variables]]
id = "position"
description = "位置"
default = "工信部合作单位"

[[variables]]
id = "work1"
description = "工作"
default = "日常补补漏洞"

[[variables]]
id = "work2"
description = "工作2"
default = "未来遏制美国互联网发展的能力"

[[variables]]
id = "punishment"
description = "惩罚"
default = "暂停6个月合作"

[templates]
main = ["其实，{org}对{person}是有一点失望的，当初{time}的时候，期望是高于{person}的实力水平的。{position}这个位置，不是{work}就可以的，要有{work2}的能力，需要有体系化思考的能力。{person}做的这个事情，价值点在哪里？是否作出了壁垒，形成了核心竞争力？和其他人的差异化在哪里？是否沉淀了一套可复用的物理资料和方法论？为什么是你{person}来做，其他人不能做吗？需要有自己的判断力，而不是{org}说什么你做什么。后续{org}希望看到{person}的思考，而不仅仅是汇报进度。今年先给{person}{punishment}，当你最痛苦的时候才是你成长最快的时候。加油💪"]
```
