### ISSUE TITLE
那种勃勃生机万物竞发的境界犹在眼前

### ISSUE THREAD

**Issue by lhy1024** [disksing/sao-gen-gen#25]
来源：大决战·淮海战役

```toml

[[variables]]
id = "position"
description = "位置"
default = "徐州"

[[variables]]
id = "action"
description = "动作"
default = "征战"

[[variables]]
id = "times"
description = "次数"
default = "五十余"

[[variables]]
id = "description"
description = "形容"
default = "中原"

[[variables]]
id = "history1"
description = "相关历史1"
default = "当年先总理令革命军分三路会合徐州，兴师北上，光复徐州的第二天，清帝见大势已去，宣告退位。"

[[variables]]
id = "history2"
description = "相关历史2"
default = "民国十六年四月，也正是在徐州城郊，我有幸亲率数十万健儿征讨北洋军阀孙传芳、张宗昌，大获全胜！ "

[[variables]]
id = "failure"
description = "相关失败"
default = "项羽被困垓下"

[[variables]]
id = "success"
description = "相关成功"
default = "二十年前，我从徐州踏上征途，开始了第二次北伐，中华秋海棠遂归于一统。"

[[variables]]
id = "self"
description = "自称"
default = "本党本军"

[templates]
main = [
"""
{position}地方，历代大规模{action}{times}次，是非曲折难以论说，但史家无不注意到，正是在这个古战场，决定了多少代{}的盛衰兴亡、此兴彼落，所以古来就有问鼎{description}之说。

{history1}{history2}

我不明白，为什么大家都在谈论着{failure}，仿佛这{description}古战场对我们决定了凶多吉少。{success}，{self}所到之处，民众竭诚欢迎，真可谓占尽天时，那种勃勃生机、万物竟发的境界，犹在眼前。短短二十年之后，这里竟至于一变而成为我们的葬身之地了么？ 
"""
]
```
