### ISSUE TITLE
我说总座高见

### ISSUE THREAD

**Issue by lhy1024** [disksing/sao-gen-gen#26]
来源：大决战·淮海战役

```toml

[[variables]]
id = "person1"
description = "人物1"
default = "刘峙"

[[variables]]
id = "person2"
description = "人物2"
default = "邱清泉"

[[variables]]
id = "position"
description = "某项事情"
default = "徐州"

[[variables]]
id = "importance"
description = "事情的重要性"
default = "京沪的大门"

[[variables]]
id = "work"
description = "莫名奇妙的言论"
default = "遇有攻击便把屁股偎依着墙壁，让你抓不着尾巴，终于把它无可奈何，弄不好尖牙利齿给你一口，咬住了就不放。"

[[variables]]
id = "english"
description = "一段外语"
default = "Stank tones, fun of foolish talk.（奇谈怪论，满嘴放屁）"

[[variables]]
id = "title"
description = "对人物1的尊称"
default = "总座"

[templates]
main = [
"""
{person1}：诸位，借此机会，我要先说几句话。最近常有人叽叽喳喳，拿我来开心，说什么{position}是{importance}，应当派一员虎将来坐镇。派不出一只虎，也要派一只狗，最后派了一只猪来。
{person1}：这话实在是恭维我啦。古今征战，猪的战术一再为人们成功运用着，{work}。
{person2}：{english}
{person1}：{person2}，你在说什么呢？
{person2}：我说{title}高见。
"""
]
```
