### ISSUE TITLE
在过去的一天

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#31]
来源：网络

```toml
[[variables]]
id = "websites"
description = "网站"
default = "知乎、贴吧、微博"

[[variables]]
id = "org"
description = "组织"
default = "b站"

[[variables]]
id = "org"
description = "组织"
default = "b站"

[[variables]]
id = "author"
description = "作者"
default = "bilibili 陈睿，bishi"

[[variables]]
id = "date"
description = "日期"
default = "2016年5月24日"

[templates]

# 'main' 模板展开后是最终的输出
main = [
"""
过去的一天，我们注意到在{websites}，有很多用户在关心着{org}，有部分用户在担心{org}会不会变成他们不喜欢的样子。

我们感谢大家的关心，你们对{org}的支持是我们坚持做{org}的动力。

在此，我可以肯定的告诉大家：{org}未来有可能会倒闭，但绝不会变质。

{autohr}
{date}
"""
]
```
