### ISSUE TITLE
足球圣经

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#32]
source https://zh.moegirl.org.cn/index.php?title=%E8%84%B8%E9%83%BD%E4%B8%8D%E8%A6%81%E4%BA%86

```toml

[[variables]]
id = "subject"
description = "主题"
default = "中国足球"

[[variables]]
id = "change"
description = "改变"
default = "足球协会主席"

[[variables]]
id = "person"
description = "人"
default = "卡马乔"

[[variables]]
id = "oldteam"
description = "原先团队"
default = "西班牙队"

[[variables]]
id = "person2"
description = "被举例的人"
default = "赵鹏"

[[variables]]
id = "action"
description = "举例的事情（动词）"
default = "踢"

[[variables]]
id = "action"
description = "举例的事情（名词）"
default = "中卫"

[[variables]]
id = "outcome1"
description = "预期后果1"
default = "输越南"

[[variables]]
id = "outcome2"
description = "预期后果2"
default = "泰国队输完输越南"

[[variables]]
id = "outcome3"
description = "预期后果3"
default = "输缅甸"

[[variables]]
id = "outcome4"
description = "预期后果4"
default = "没人输了"

[[variables]]
id = "reality"
description = "现实情况"
default = "比赛本身就没有打好基础"

[[variables]]
id = "dream"
description = "幻想"
default = "在17年或者16年这样关键比赛他能赢"

[[variables]]
id = "suggest"
description = "建议"
default = "把自己战术打法，足球的这个理念先搞懂"

[[variables]]
id = "person3"
description = "推荐的人"
default = "小高（高洪波）"

[[variables]]
id = "blackhistory"
description = "黑历史"
default = "在合肥输个1:5"

[templates]

# 'main' 模板展开后是最终的输出
main = [
"""
“你说{subject}啊，一届一届换了多少{change}了，改过吗？换汤不换药啊，人家{person}也有理由说的，我（曾经）带的是什么队，我带的是{oldteam}，你这批人是什么人啊，你叫我带。{subject}现在什么水平，就那么几个人，你{person2}什么的都在{action1}{action2}，他能{action1}吗？{action1}不了！没这个能力知道吗？再下去就要{outcome1}了，{outcome2}，再{outcome3}，接下来{outcome4}。”

“哎哟，谢天谢地了，谢天谢地，你像这样的{reality}，你能跟我保证{dream}啊！务实一点，我劝你们，我{suggest}，{person3}带的蛮好的，你把他去换了干什么，你{blackhistory}，你倒告诉我怎么解释，脸都不要了。”
"""]
```
