### ISSUE TITLE
测试生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#4]
```toml
# variables 是需要用户填入的文本变量，可以有多个，每个对应生成器的一个输入框。

[[variables]]
# 每个变量的唯一 id，在模板中通过{id}的形式引用
id = "subject"

# 输入框左边的提示信息
description = "主题"

# 页面初始化时的默认值，建议写一个例子便于用户理解
default = "桃核"

# 第二个变量

[[variables]]
id = "event"
description = "描述"
default = "不能整个吞下去"

# 模板可以有很多个，每个模板有唯一 id 和文本列表
# 模板可以通过{id}的形式引用变量或其他模板（允许递归调用）
# 当模板展开时，会从列表中随机选一个
# 通过组合模板，可以搞出比较复杂的结构，参考下“胡编生成器”

[templates]

# 2选1
p1 = ["{subject}{event}是怎么回事呢？", "{subject}相信大家都很熟悉，但是{event}是怎么回事呢？"]

# toml 支持多行文本
p2 = [
"""
那么{subject}为什么会{event}，相信大家都很好奇。大家可能会感到很惊讶，{subject}怎么会{event}呢？但事实就是这样，小编也感到非常惊讶。那么这就是关于{subject}{event}的事情了，大家有没有觉得很神奇呢？
看了今天的内容，大家有什么想法呢？欢迎在评论区告诉小编一起讨论哦。
"""
]

# 'main' 模板展开后是最终的输出
main = [{p1}{p2}]
```
