### ISSUE TITLE
凭啥你不用生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#40]
```toml

[[variables]]
id = "person"
description = "人物"
default = "同事"

[[variables]]
id = "subject"
description = "主题"
default = "Kubernetes"

[[variables]]
id = "pros"
description = "好处"
default = "云原生事实标准，声明式API，繁荣的用户生态"

[[variables]]
id = "cons"
description = "坏处"
default = "检查yaml格式错误"

[templates]
main = [
"""
{person}跟我聊{subject}的好处，比如{pros}，越聊越激烈，后来见我一阵说服无效后，接近咆哮地说了一句：我们{cons}这么辛苦，凭啥你不用？
然后两人陷入沉默……
"""]
```
