### ISSUE TITLE
理工科设计的玩意儿

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#43]
Source https://twitter.com/onlyswan/status/1554002700953481217?s=20&t=S6de1NZkpkmSORQaxRRk7g

```toml

[[variables]]
id = "what"
description = "主题"
default = "路由器"

[[variables]]
id = "where"
description = "位置"
default = "设置页面"

[[variables]]
id = "glossary"
description = "术语"
default = "DHCP，掩码，MAC，WDS，地址池，DNS"

[[variables]]
id = "example"
description = "例子"
default = "想用旧路由器弄个桥接"

[[variables]]
id = "confuse"
description = "困惑"
default = "桥还接"

[templates]

main = [
"""
{what}这种理科男设计出来的玩意儿，真是要命。

{where}里没有几句人话，全是黑话和暗语，{glossary}……只有他们能懂。正常人不可能看懂。

{example}——看看，全是这种黑话，{confuse}。这是人话吗？

弄了半天，一头大汗，也没弄明白。

网上所谓的教程，是同一帮人写的，用同一套黑话。

不弄了……
"""
]
```
