### ISSUE TITLE
设计稿评价

### ISSUE THREAD

**Issue by lorrylockie** [disksing/sao-gen-gen#45]
```toml
# variables 是需要用户填入的文本变量，可以有多个，每个对应生成器的一个输入框。

[[variables]]
# 每个变量的唯一 id，在模板中通过{id}的形式引用
id = "gao"

# 输入框左边的提示信息
description = "设计稿的名字"

# 页面初始化时的默认值，建议写一个例子便于用户理解
default = "Polibeli 的设计稿"

# 第二个变量

[[variables]]
id = "desc"
description = "设计不好的理由"
default = "缺乏质感"

# 模板可以有很多个，每个模板有唯一 id 和文本列表
# 模板可以通过{id}的形式引用变量或其他模板（允许递归调用）
# 当模板展开时，会从列表中随机选一个
# 通过组合模板，可以搞出比较复杂的结构，参考下“胡编生成器”

# 第三个变量

[[variables]]
id = "desc2"
description = "设计不好的理由 2"
default = " 缺乏美感"

# 模板可以有很多个，每个模板有唯一 id 和文本列表
# 模板可以通过{id}的形式引用变量或其他模板（允许递归调用）
# 当模板展开时，会从列表中随机选一个
# 通过组合模板，可以搞出比较复杂的结构，参考下“胡编生成器”

[templates]

# 2选1
p1 = ["{gao}我觉得还是差点意思，虽然设计要求上满足了基本功能，但从视觉传达上差点意思。为什么这么说呢"]

# toml 支持多行文本
p2 = [
"""
一方面我觉得我们视觉上还是要加强，品牌也要加强，排版也要加强。否则这个 {gao} 怎么打动用户呢。
"""
]


p3 = [
"""
另外一方面，方面我觉得有点丑，质感不强，我也说不出什么专业的评价，这是个很难的问题，我不专业

但如果一定要说，我觉得是 {desc}, 如果还要再说，我觉得是 {desc2}
"""
]

# 'main' 模板展开后是最终的输出
main = ["{p1}{p2}{p3}"]
```
