### ISSUE TITLE
我的舞台生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#51]
source: https://twitter.com/season696/status/1559799663267823617

```toml

[[variables]]
id = "subject"
description = "主题"
default = "学习"

[[variables]]
id = "childhood"
description = "儿时经历"
default = "就就读于上海国际学校"

[[variables]]
id = "cost-type"
description = "花费类型"
default = "学费"

[[variables]]
id = "cost-amount"
description = "花费数量"
default = "300多万"

[[variables]]
id = "interests1"
description = "爱好1"
default = "英语，写歌，音乐，唱歌，跳舞，表演，播音，滑雪冲浪，高尔夫...雅思课裸考6分"

[[variables]]
id = "interests2"
description = "爱好2（可以与爱好1有部分重复）"
default = "钢琴、词曲创作、播音"

[[variables]]
id = "goal"
description = "目标（可以与爱好1/2有部分重复）"
default = "影视、音乐"

[[variables]]
id = "non-goal"
description = "伪目标"
default = "容貌哗众取宠"

[[variables]]
id = "resource"
description = "优越条件"
default = "想读书马上就可以飞到美国伯克利就读"

[templates]
main = [
"""
我{childhood}，从未停止{subject}的脚步。

{cost-type}都花了{cost-amount}，我{subject}之余爱好很多 {interests1}，{subject}并不是我的弱点。我还自己{subject}了{interests2}，从来都不是只为了{non-goal}。我{resource}，希望自己现在开始可以在{goal}方面给大家一个交代。

期待我的舞台。
"""
]
```
