### ISSUE TITLE
暴论生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#56]
source: https://twitter.com/Soulogic/status/1562267125397348357

```toml

[[variables]]
id = "subject"
description = "主题"
default = "《沙丘》"

[[variables]]
id = "category"
description = "分类"
default = "古典科幻"

[[variables]]
id = "concept"
description = "概念"
default = "想象力"

[[variables]]
id = "examples"
description = "举例"
default = "星球大战里的激光枪牛仔、基地的银河版罗马帝国衰亡史"

[[variables]]
id = "rating"
description = "评价"
default = "科幻经典"

[templates]
main = ["{subject}真没看过，我通常对{category}敬而远之。不过倒是能理解所说的“{concept}”是什么情况，如{examples}，在我看来是最无趣的东西，但有些人奉之为{rating}"]
```
