### ISSUE TITLE
尖端技术

### ISSUE THREAD

**Issue by sticnarf** [disksing/sao-gen-gen#60]
```toml
# variables 是需要用户填入的文本变量，可以有多个，每个对应生成器的一个输入框。

[[variables]]
# 每个变量的唯一 id，在模板中通过{id}的形式引用
id = "subject"

# 输入框左边的提示信息
description = "主题"

# 页面初始化时的默认值，建议写一个例子便于用户理解
default = "ML"

[templates]

# toml 支持多行文本
p1 = [
"""
很多懂 {subject} 的人用 {subject} 是因为他们只会用 {subject}，不懂 {subject} 的人用 {subject} 是因为他们想借这个机会上手 {subject}。

至于这个问题适不适合用 {subject}，有没有比 {subject} 更简单的办法，没有人知道，也没有人想知道 🙃
"""
]

# 'main' 模板展开后是最终的输出
main = ["{p1}"]
```
