### ISSUE TITLE
没有人知道生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#61]
source: https://twitter.com/the_foreverbell/status/1565361797908930561?s=20&t=LmXfnE_hioe7iPvFiLId5g

```toml
[[variables]]
id = "subject"
description = "主题"
default = "ML"
[templates]
# 'main' 模板展开后是最终的输出
main = ["""
很多懂{subject}的人用{subject}是因为他们只会用{subject}，不懂{subject}的人用{subject}是因为他们想借这个机会上手{subject}。

至于这个问题适不适合用{subject}，有没有比{subject}更简单的办法，没有人知道，也没有人想知道 🙃
"""]
```
