### ISSUE TITLE
找工作传闻生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#63]
source: https://twitter.com/haricheung/status/1569536077496733696

```toml
[[variables]]
id = "person"
description = "人物"
default = "vue作者尤雨溪"

[[variables]]
id = "person2"
description = "尤人物简称"
default = "尤"

[[variables]]
id = "company"
description = "公司"
default = "拼多多"

[[variable]]
id = "promise1"
description = "承诺1"
default = "把vue改名pue"

[[variable]]
id = "promise2"
description = "承诺2"
default = "在框架内执行this.xx=xx的时候自动跳转拼多多砍一刀"

[[variable]]
id = "promise3"
description = "承诺3"
default = "接受007的工作模式"

[[variable]]
id = "promise4"
description = "承诺4"
default = "把陪老婆孩子的时候奉献给工作"

[[variable]]
id = "refuse1"
description = "拒绝理由1"
default = "年纪太大"

[[variable]]
id = "refuse2"
description = "拒绝理由2"
default = "没有太多的潜力"

[templates]
main = ["传闻{person}曾三次面试{company}失败。{person2}甚至一度要{promise1}，并{promise2}。{person2}还说可以{promise3}，并愿意{promise4}。但是最后还是被{company}HR一口回绝，认为{person2}{refuse1}，{refuse2}。"]
```
