### ISSUE TITLE
认识了一个人生成器

### ISSUE THREAD

**Issue by disksing** [disksing/sao-gen-gen#65]
source: https://twitter.com/Gauge_Boson_/status/1570351129111965696

```toml

[[variables]]
id = "person"
description = "人物"
default = "理学学士"

[[variables]]
id = "topic1"
description = "话题1"
default = "辛几何"

[[variables]]
id = "topic2"
description = "话题2"
default = "弦论，聊拓扑学"

[[variables]]
id = "topic3"
description = "话题3"
default = "李群和李代数的关系"

[[variables]]
id = "topic4"
description = "第二天的话题"
default = "问我前端好不好学"


[templates]
main = ["6月1日，认识了一个{person}，他跟我聊{topic1}，聊{topic2}，聊{topic3}。6月2日，他{topic4}。"]
```
