### ISSUE TITLE
关系不错的同事跑过来跟我说生成器

### ISSUE THREAD

**Issue by wey-gu** [disksing/sao-gen-gen#68]
source: https://twitter.com/disksing/status/1583360121089839104

```toml
[[variables]]
id = "SNS"
description = "社媒"
default = "推特"

[[variables]]
id = "topic"
description = "主题"
default = "怀孕"

[[variables]]
id = "event"
description = "悲伤"
default = "笑出声来"

[templates]
main = [
"""
刚才一个关系还不错的同事跑过来跟我说，看到我天天在{SNS}上编{topic}段子搞到了很多粉丝，现在流量有收入没，还和旁边的人开始大声讨论我到底是不是真要{topic}。

哎我他妈结交的都是些什么人，悲伤到忍不住{event}。
"""
]
```
