### ISSUE TITLE
少妇白洁生成器

### ISSUE THREAD

**Issue by rainyricew** [disksing/sao-gen-gen#82]
```toml
# variables 是需要用户填入的文本变量，可以有多个，每个对应生成器的一个输入框。

[[variables]]
# 每个变量的唯一 id，在模板中通过{id}的形式引用
id = "female"

# 输入框左边的提示信息
description = "角色1"

# 页面初始化时的默认值，建议写一个例子便于用户理解
default = "白洁"

# 第二个变量

[[variables]]
id = "male"
description = "角色2"
default = "东子"

# 模板可以有很多个，每个模板有唯一 id 和文本列表
# 模板可以通过{id}的形式引用变量或其他模板（允许递归调用）
# 当模板展开时，会从列表中随机选一个
# 通过组合模板，可以搞出比较复杂的结构，参考下“胡编生成器”

[templates]

# 2选1
p1 = [
"当{female}柔柔的小手被{male}忽然握住，那种近乎挑逗的动作让{female}心里不由得阵阵发热。"
"看{female}没有反对，{male}挪到了{female}的身边，拉着{female}的手微微一拉，{female}软软的身子就靠在了{male}身上。{male}右手搂在{female}乳房的下边，嘴从{female}的秀发吻过，吻到{female}的额头，{female}微微地仰起头，粉红柔软的嘴颤抖着上了{male}火热的嘴，仿佛两块磁石一样两人就吸在了一起。"
"{female}的双手抬起来抱住了{male}的脖子，嘴纠在一起不断的摩擦、，滑软跳动的舌尖在两人舌之间滑动，阵阵绵软的娇呻从两人紧紧贴在一起的嘴间飘出。"
"两人搂在一起纠缠，{male}的手撩起{female}小衬衫的底襟，大手轻轻地摩挲着{female}光滑平坦的小腹，感受着{female}身体阵阵微微的颤动。"
"{female}软软的身子侧靠在{male}身上，双手环抱着{male}的脖子，雪白的紧身小衬衫只有两个扣子还扣在一起，伴随着阵阵的呢喃和娇吟，{female}趁着浓浓的醉意完全沉浸在了和兴奋之中。"
"{male}的手从{female}的前出来，手伸下去摸到了{female}柔软感的玲珑小脚，隔着滑滑软软的丝袜，顺着{female}的小腿慢慢向上滑动。"
]

# toml 支持多行文本
p2 = [

"“{male}，我就要毕业了，我要是毕不了业，回家我怎么交待呀？”"
"{female}声泪俱下的哭着，{male}却丝毫不为之所动，眼睛扫视着{female}薄薄的t恤下鼓鼓的乳房。“这可很难，我已经报到学校里了，除非……”{male}的手忽然从{female}的肩头滑落到了丰满的乳房上，{female}浑身一抖，“啊，你干什么？”{female}一下站了起来。”
““打开天窗说亮话，就是你让我玩一次，我马上再给你一张试卷，包你能毕业。”{male}色迷迷的还要去摸{female}的脸蛋。"
"{female}脸一下红了“这……我……”"
"“你要是敢就快点，我老婆一会儿就回来了，顶多还有四十分钟。怎样，行不行？”{male}很不耐烦的样子。"
"{female}心都快跳出来了，哪里想到这个呀，动都不敢动。{male}一看{female}的样子，一把就抓住了{female}的胳膊把{female}搂在怀里，手顺势就握住了{female}那柔软又有着青春弹性的小巧乳房。"
"{male}的手伸到了{female}的裙子里面，摸到了{female}光滑的长腿，{female}浑身发抖紧闭着眼睛，任由他乱摸。"

]

# 'main' 模板展开后是最终的输出
main = ["{p1}{p2}"]
```
