### ISSUE TITLE
test

### ISSUE THREAD

**Issue by bobby285271** [disksing/sao-gen-gen#9]
```toml
[[variables]]
id = "subject"
description = "主题"
default = "胖头鱼"

[templates]
main = [
"""
这{subject}啊，拿铁锅用大酱炖，老好吃了。
"""
]
```
