### ISSUE TITLE
找找自己原因

### ISSUE THREAD

**Issue by heyanlong** [disksing/sao-gen-gen#93]
```toml

[[variables]]
id = "argue"
description = "质疑内容"
default = "贵了"

[[variables]]
id = "refute"
description = "反驳"
default = "这个价格"

[[variables]]
id = "subject"
description = "主题"
default = "房子"

[[variables]]
id = "subject-attr"
description = "主题属性"
default = "房价"

[[variables]]
id = "subject-attr-alias"
description = "主题属性别名"
default = "价格"

[[variables]]
id = "subject-func"
description = "主题功能"
default = "住"

[[variables]]
id = "event"
description = "事件"
default = "上涨"

[[variables]]
id = "reason"
description = "原因"
default = "市场供需关系"

[[variables]]
id = "complain"
description = "抱怨"
default = "房价贵"

[templates]

p1 = [
"""
哪里{argue}?
这么多年都是{refute}，好不好，不要睁着眼睛乱说，{subject-attr}是市场决定的，不是我能控制的。
况且，国内的{subject-attr}一直都在{event}，这是{reason}决定的。不要怪{complain}，要找找自己原因，
好不好，这么多年了工资涨没涨，有没有认真工作，好不? {subject-attr}是用来{subject-func}的，
不要总是看它的{subject-attr-alias}，要看它的实际价值。
"""
]

main = ["{p1}"]
```
